name: utils
description:
  This package will use contain utils for app. If don't know using what util, you maybe create your function
  in Utils file.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Black.ttf
        - asset: lib/assets/fonts/Inter-Bold.ttf
        - asset: lib/assets/fonts/Inter-ExtraBold.ttf
        - asset: lib/assets/fonts/Inter-ExtraLight.ttf
        - asset: lib/assets/fonts/Inter-Light.ttf
        - asset: lib/assets/fonts/Inter-Medium.ttf
        - asset: lib/assets/fonts/Inter-Regular.ttf
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
        - asset: lib/assets/fonts/Inter-Thin.ttf

  assets:
    - lib/assets/images/
    - lib/assets/icons/
